In [4]:
!pip install torch

In [ ]:
!pip install lightning

In [3]:
import numpy as np 
import torch
from torch import nn
from torch.utils.data import Dataset
import pytorch_lightning as pl
from torchmetrics import MeanSquaredError
import matplotlib.pyplot as plt

pl.seed_everything(32)

Seed set to 32


32

In [8]:
scalar = torch.tensor(3.0)
vector = torch.tensor([3.0,1.0])
matrix = torch.tensor([[3.0, 1.0], [3.0, 1.0]])
print(f" scalar {scalar} shape {scalar.shape}")
print(f" vector {vector} shape {vector.shape}")
print(f" matrix {matrix} shape {matrix.shape}")

 scalar 3.0 shape torch.Size([])
 vector tensor([3., 1.]) shape torch.Size([2])
 matrix tensor([[3., 1.],
        [3., 1.]]) shape torch.Size([2, 2])


In [6]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([[1.0, 2.0, 3.0]])

In [7]:
a * b 

array([[1., 4., 9.]])

In [9]:
np_array = np.array([1.0, 2.0, 3.0])
torch_tensor = torch.tensor([1.0, 2.0, 3.0])

In [10]:
print(f" Numpy result {np_array * 2}")
print(f" Torch result {torch_tensor * 2}")

 Numpy result [2. 4. 6.]
 Torch result tensor([2., 4., 6.])


In [12]:
print(f" Numpy result {np_array * np_array}")
print(f" Torch result {torch_tensor * torch_tensor}")

 Numpy result [1. 4. 9.]
 Torch result tensor([1., 4., 9.])


In [14]:
print(f" Numpy result {np_array + np_array}")
print(f" Torch result {torch_tensor + torch_tensor}")

 Numpy result [2. 4. 6.]
 Torch result tensor([2., 4., 6.])


In [16]:
print(f" Numpy result {np_array.mean()}")
print(f" Torch result {torch_tensor.mean()}")

 Numpy result 2.0
 Torch result 2.0


In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Selected device {device}")

Selected device cpu


In [18]:
x_cpu = torch.tensor([1.0, 2.0, 3.0])

In [19]:
device

device(type='cpu')

In [20]:
x_device = x_cpu.to(device)

In [21]:
x_device 

tensor([1., 2., 3.])

In [22]:
x = torch.tensor(2.0, requires_grad=True)

In [28]:
y = x ** 2 + 3 * x + 1
y.backward()

In [24]:
y 

tensor(11., grad_fn=<AddBackward0>)

In [26]:
dy = 2*x + 3
dy 

tensor(7., grad_fn=<AddBackward0>)

In [30]:
print(f"x: {x} y: {y}")
print(f"dy/dx at x = 2 {x.grad.item()}")

x: 2.0 y: 11.0
dy/dx at x = 2 7.0


In [31]:
x.grad

tensor(7.)

In [33]:
x = torch.tensor(4.0, requires_grad=True)
y = x**4 + 4
y.backward()
print(f"dy/dx at x = 4.0 {x.grad.item()}")

dy/dx at x = 4.0 256.0


## Neural Networks


In [42]:
class TinyNetwork (nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=1, out_features=4)
        self.actication = nn.ReLU()
        self.layer2 = nn.Linear(in_features=4, out_features=1)
    def forward(selt,x) :
        x = selt.layer1(x)
        x = selt.actication(x)
        x = selt.layer2(x)
        return x    
    



In [43]:
model = TinyNetwork()
example_input = torch.tensor([[2.0]])
example_output = model(example_input)
print(example_output)

tensor([[0.1532]], grad_fn=<AddmmBackward0>)


In [44]:
class TinyNetwork (nn.Module): ##2 Input more complec hidden layer output 1
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=2, out_features=8)
        self.actication = nn.ReLU()
        self.layer2 = nn.Linear(in_features=8, out_features=1)
    def forward(selt,x) :
        x = selt.layer1(x)
        x = selt.actication(x)
        x = selt.layer2(x)
        return x    

In [45]:
x = torch.tensor([[0.0],[1.0],[2.0],[3.0]])
y = torch.tensor([[1.0],[2.0],[4.0],[6.0]])

In [46]:
import torch
from torch.utils.data import Dataset, DataLoader

class TinyDataset(Dataset):
    def __init__(self):
        self.x = torch.tensor([[0.0], [1.0], [2.0], [3.0]])
        self.y = torch.tensor([[1.0], [2.0], [4.0], [6.0]])

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return self.x[index], self.y[index], 1

dataset = TinyDataset()
print(len(dataset))

x, y, z = dataset[3]
print(f"x:{x} - y:{y}")

loader = DataLoader(dataset, batch_size=2, shuffle=False)

for batch_x, batch_y, batch_z in loader:
    print(f"batch_x = {batch_x}")

4
x:tensor([3.]) - y:tensor([6.])
batch_x = tensor([[0.],
        [1.]])
batch_x = tensor([[2.],
        [3.]])


In [ ]:
pure_model = TinyNetwork()
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(pure_model.parameters(), lr=0.01)

for epoch in range(3):
    for i, (batch_x, batch_y, _) in enumerate(loader):
        prediction = pure_model(batch_x)
        loss = loss_fn(prediction, batch_y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"epoch {epoch} - batch {i} - loss = {loss.item()}")

ValueError: too many values to unpack (expected 2)